services:
    _defaults:
        autoconfigure: true
        autowire: true

    HeimrichHannot\QnaBundle\:
        resource: '../src/'
        exclude:
            - '../src/ContaoManager/'
            - '../src/HeimrichHannotQnaBundle.php'
