name: CI

on:
  pull_request:
  push:

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: dom, fileinfo, filter, gd, intl, mbstring, pdo_mysql, simplexml, xml, xmlreader, xmlwriter
          coverage: none

      - name: Install the dependencies
        uses: ramsey/composer-install@v3

      - name: Validate composer.json
        run: composer validate --strict

      - name: PHP-CS-Fixer
        run: vendor/bin/php-cs-fixer check --diff --sequential

      - name: PHPStan
        run: vendor/bin/phpstan analyse --no-progress

      - name: PHPUnit
        run: vendor/bin/phpunit
